### PR TITLE
Handle undefined body when there's a response without one

### PR DESCRIPTION
**Pull request by todoubled**
This is the proper version of
https://github.com/plaid/plaid-node/pull/104 and should resolve https://github.com/plaid/plaid-node/issues/97

### CODE REVIEW

**Comment by michaelckelly** [comment]
Thanks for the build @todoubled - I just enabled CI for fork'd PRs. Could you force push to this branch to trigger a run? My hunch is lint my fail with the equality check / quotes.

**Comment by michaelckelly** [comment]
LGTM

**Comment by michaelckelly** [comment]
@todoubled - `plaid-legacy@1.2.1` was just published with this fix -- thanks!

**Comment by todoubled** [comment]
Thanks @michaelckelly!

**Pull request merged**
